version: '3.9'
services:

  run-action-server:
    container_name: bot-action-server
    image: riaee/byk:bot-action-server-v0.122
    ports:
      - 5055:5055
    volumes:
      - ./bot_data/actions:/app/actions
      - ./bot_data/data:/app/data
    command:
      - start
      - --actions
      - actions
    restart: always
    networks:
      - bykstack

  byk-bot:
    container_name: byk-bot
    image: riaee/byk:bot-v0.133
    ports:
      - 5005:5005
    volumes:
      - ./bot_data/:/app
      - ./cc.et.300.bin:/app/fasttext_et_model/cc.et.300.bin:ro
    command:
      - run
    restart: always
    networks:
      - bykstack

networks:
  bykstack:
    name: bykstack
    driver: bridge
